---
- name: test
  hosts: centos
  gather_facts: no
  tasks:
  - name: test
    command: ssh -o ConnectTimeout=5 {{ inventory_hostname }} uptime
    delegate_to: 127.0.0.1
    register: results
    ignore_errors: yes
  - name: Sending an e-mail using the remote machine, not the Ansible controller node
    mail:
#     host: localhost
     host: 192.168.122.139
     port: 25
     from: veera@test.com
#     to: devops
     to: root@localhost.localdomain
     subject: Ansible - System {{ inventory_hostname }} is not reachable
     body: Please check the server {{ inventory_hostname }} 
#    when: "'Connection timed out during banner exchange' in results.stderr" 
#    when: ("'Connection timed out during banner exchange' in results.stderr") or ("'"ssh_exchange_identification: Connection closed by remote host"' in results.stderr")
    when:  results.rc == 255
    delegate_to: 127.0.0.1
#  - name: print result
#    debug:
#      msg: '{{ results.stderr }}'
